### ISSUE TITLE
菜单-404 怎么破

### ISSUE THREAD

**Issue by zhuhengli** [agamgn/ssm-Online_Examination#1]

**Comment by agamgn** [comment]
> 
> 
> _No description provided._

你好，能描述具体点吗

**Comment by zhuhengli** [comment]
没事了，页面bug 我自己调好了
 感谢分享




------------------ 原始邮件 ------------------
发件人: "agamgn"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 下午2:01
收件人: "agamgn/ssm-Online_Examination"<ssm-Online_Examination@noreply.github.com>;
抄送: "青城"<542543442@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [agamgn/ssm-Online_Examination] 菜单-404 怎么破 (#1)



 
No description provided.
  
你好，能描述具体点吗

**Comment by agamgn** [comment]
> 
> 没事了，页面bug 我自己调好了 感谢分享
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "agamgn"<notifications@github.com>; 发送时间: 2019年5月9日(星期四) 下午2:01 收件人: "agamgn/ssm-Online_Examination"<ssm-Online_Examination@noreply.github.com>; 抄送: "青城"<542543442@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [agamgn/ssm-Online_Examination] 菜单-404 怎么破 (#1) No description provided. 你好，能描述具体点吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

好的，多交流

**Comment by zhongmax** [comment]
请教一下，404修复的？
